require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppSettingsController do

  # This should return the minimal set of attributes required to create a valid
  # AppSetting. As you add validations to AppSetting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all app_settings as @app_settings" do
      app_setting = AppSetting.create! valid_attributes
      get :index
      assigns(:app_settings).should eq([app_setting])
    end
  end

  describe "GET show" do
    it "assigns the requested app_setting as @app_setting" do
      app_setting = AppSetting.create! valid_attributes
      get :show, :id => app_setting.id
      assigns(:app_setting).should eq(app_setting)
    end
  end

  describe "GET new" do
    it "assigns a new app_setting as @app_setting" do
      get :new
      assigns(:app_setting).should be_a_new(AppSetting)
    end
  end

  describe "GET edit" do
    it "assigns the requested app_setting as @app_setting" do
      app_setting = AppSetting.create! valid_attributes
      get :edit, :id => app_setting.id
      assigns(:app_setting).should eq(app_setting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AppSetting" do
        expect {
          post :create, :app_setting => valid_attributes
        }.to change(AppSetting, :count).by(1)
      end

      it "assigns a newly created app_setting as @app_setting" do
        post :create, :app_setting => valid_attributes
        assigns(:app_setting).should be_a(AppSetting)
        assigns(:app_setting).should be_persisted
      end

      it "redirects to the created app_setting" do
        post :create, :app_setting => valid_attributes
        response.should redirect_to(AppSetting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved app_setting as @app_setting" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppSetting.any_instance.stub(:save).and_return(false)
        post :create, :app_setting => {}
        assigns(:app_setting).should be_a_new(AppSetting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppSetting.any_instance.stub(:save).and_return(false)
        post :create, :app_setting => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested app_setting" do
        app_setting = AppSetting.create! valid_attributes
        # Assuming there are no other app_settings in the database, this
        # specifies that the AppSetting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AppSetting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => app_setting.id, :app_setting => {'these' => 'params'}
      end

      it "assigns the requested app_setting as @app_setting" do
        app_setting = AppSetting.create! valid_attributes
        put :update, :id => app_setting.id, :app_setting => valid_attributes
        assigns(:app_setting).should eq(app_setting)
      end

      it "redirects to the app_setting" do
        app_setting = AppSetting.create! valid_attributes
        put :update, :id => app_setting.id, :app_setting => valid_attributes
        response.should redirect_to(app_setting)
      end
    end

    describe "with invalid params" do
      it "assigns the app_setting as @app_setting" do
        app_setting = AppSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppSetting.any_instance.stub(:save).and_return(false)
        put :update, :id => app_setting.id, :app_setting => {}
        assigns(:app_setting).should eq(app_setting)
      end

      it "re-renders the 'edit' template" do
        app_setting = AppSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppSetting.any_instance.stub(:save).and_return(false)
        put :update, :id => app_setting.id, :app_setting => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested app_setting" do
      app_setting = AppSetting.create! valid_attributes
      expect {
        delete :destroy, :id => app_setting.id
      }.to change(AppSetting, :count).by(-1)
    end

    it "redirects to the app_settings list" do
      app_setting = AppSetting.create! valid_attributes
      delete :destroy, :id => app_setting.id
      response.should redirect_to(app_settings_url)
    end
  end

end
